name: Build

permissions: {}

on:
  pull_request:
  push:

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: linux
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build --release
    - run: sh test.sh
